katalog/urls.py
# Implementasi routing terhadap views.py
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
# Implementasi routing terhadap views.py
from django.urls import path
from todolist.views import delete_task, get_task_json, show_todolist, show_todolist_new,create_task, register, login_user, logout_user, delete_task, update_task, add

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('new/', show_todolist_new, name="show_todolist_new"),

    path('add/', add, name="add"),
    path('json/', get_task_json, name="get_task_json"),

    path('create-task/', create_task, name='create_task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete-task/<int:id>', delete_task, name='delete-task'),
    path('update-task/<int:id>', update_task, name='update-task'),
] 

todolist/models.py
from django.contrib.auth.models import User
from django.db import models

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task
from django.forms import TextInput


class CreateNew(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Insert task title..',
                'required': 'False'
                }),
            'description': TextInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Insert task description..',
                'required': 'False'
                })
        }

todolist/views.py
from urllib import response
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, HttpResponseForbidden
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from todolist.forms import CreateNew
from todolist.models import Task
from django.core import serializers

# ============================/ASSIGNMENT 4/============================

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    task_list = Task.objects.all()
    task_data=[]
    user = request.user

    for task in task_list:
        if task.user == user:
            task_data.append(task)
    context = {
        'task_data':task_data,
        'name' : request.user,
    }
    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    # Memanggil CreateNew dari forms.py
    task_form = CreateNew(request.POST)
    if request.method == 'POST':
        
            task_form = CreateNew(request.POST)
            if task_form.is_valid():
                new = task_form.save(commit=False)
                # Set the current logged in user
                task_form.instance.user = request.user
                new.save()

                response=HttpResponseRedirect(reverse("todolist:show_todolist"))
                return response

    context = {'task_form' : task_form}
    return render(request, 'create_task.html', context)

# ============================/ASSIGNMENT 6/============================

@login_required(login_url='/todolist/login/')
def show_todolist_new(request):
    task_list = Task.objects.all()
    task_data=[]
    user = request.user

    for task in task_list:
        if task.user == user:
            task_data.append(task)
    context = {
        'task_data':task_data,
        'name' : request.user,
    }
    return render(request, 'todolist_new.html', context)

#  A view which returns a JSON object from json database
def get_task_json(request):
    task_item = Task.objects.all()
    return HttpResponse(serializers.serialize('json', task_item), content_type="application/json")

# A view to add task
@login_required(login_url='/auth/login/')
def add(request):
    form = CreateNew(request.POST)
    if (form.is_valid() and request.method == 'POST'):
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task(user=user, title=title, description=description)

        # Save submitted form data to model
        task.save()

        return JsonResponse({"fields": {
            "is_finished": task.is_finished,
            "title": title,
            "description": description,
            "date": task.date,
        }})        


# =================================/AUTH/=======================================

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def delete_task(request, id):
    task_delete= Task.objects.filter(pk=id)
    task_delete.delete()
    return redirect(reverse("todolist:show_todolist"))

def update_task(request, id):
    task_update= Task.objects.get(pk=id)
    task_update.is_finished = not task_update.is_finished
    task_update.save()
    return redirect(reverse("todolist:show_todolist"))

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Task</title>
{% endblock meta %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="container d-flex justify-content-center">
    <div class = "container shadow bg-body p-4 m-4">
        <h1 class="text-center">Add Task</h1>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            <table>
                {{ task_form.as_p }}
                <tr>
                    <td><input class="btn login_btn btn-primary" type="submit" value="Add Task"></td>
                </tr>
                <tr>
                    <td><a href="{% url 'todolist:show_todolist' %}" class="btn btn-danger">Cancel</a></td>
                </tr>
            </table>
        </form>   
    </div>
</div>

{% endblock content %}

todolist/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'todolist:show_todolist' %}">Todolist</a>
                </li>
            </ul>
        </div>
        <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <span class="navbar-brand">G'day, {{user.username}}!</span>
                        <span class="navbar-brand">|</span>
                        <a class="navbar-brand" href="{% url 'todolist:logout' %}">Logout</a>
                    {% else %}
                        <a class="navbar-brand" href="{% url 'todolist:login' %}">Login</a>
                        <a class="navbar-brand" href="{% url 'todolist:register' %}">Register</a>
                    {% endif %}
                </li>
            </ul>
        </div>
        
    </div>
</nav>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% include 'header.html' %}

    <div class="container d-flex justify-content-center">
        <div class = "container shadow bg-body p-3 m-4">

            <h1 class="text-center">Login</h1>

            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>

                    <tr>
                        <td></td>
                        <td><input class="btn login_btn btn-primary" type="submit" value="Login"></td>
                    </tr>
                </table>
            </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
                
            Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
        </div>
    </div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
    {% include 'header.html' %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <div class = "container shadow p-3 mb-5 bg-body rounded align-items-center">
        
        <h1 class="text-center">Formulir Registrasi</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input class="btn btn-primary login_btn" type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

{% include 'header.html' %}

<head>
  {% load static %}
  <!-- CSS LINKS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </script>
</head>

<body>
  <div class="container p-4 d-flex justify-content-center bg-body rounded">
    <h1>Welcome to Todolist!</h1>
  </div>

  <div class="container d-flex justify-content-center bg-body rounded">
    <a href="{% url 'todolist:create_task' %}" class="btn btn-lg btn-warning">Add New Task</a>
  </div>

  
  <div class="container p-5 mb-7 bg-body rounded ">

    <div class="row row-cols-1 g-2">
      <h2 class="fw-bold">ToDos</h2>
      {% for task in task_data %}
        {% if task.is_finished == False %}
          <div class="col-md-4">
              <div class="card" style="width: 19rem;">
                <!-- card body -->
                <div class="card-body">
                  <h5 class="card-title">{{task.title}}</h5>
                  <p class="card-text">{{task.description}}</p>
                  <a href="{% url 'todolist:update-task' task.id %}" class="btn btn-outline-success btn-sm">Finished</a>
                  <a href="{% url 'todolist:delete-task' task.id %}" class="btn btn-outline-danger btn-sm">Delete Task</a>
                </div>
                <!-- card footer -->
                <div class="card-footer">
                  <small class="text-muted">{{task.date}}</small>
                </div>
              </div>
            </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>

  <div class="container p-5 mb-5 bg-body rounded">

    <div class="row row-cols-1 g-2">
      <h2 class="fw-bold">Finished Tasks</h2>
      {% for task in task_data %}
        {% if task.is_finished  %}
          <div class="col-md-4">
              <div class="card" style="width: 19rem;">
                <!-- card body -->
                <div class="card-body">
                  <h5 class="card-title">{{task.title}}</h5>
                  <p class="card-text">{{task.description}}</p>
                  <a href="{% url 'todolist:update-task' task.id %}" class="btn btn-outline-success btn-sm">Undo</a>
                  <a href="{% url 'todolist:delete-task' task.id %}" class="btn btn-outline-danger btn-sm">Delete Task</a>
                </div>
                <!-- card footer -->
                <div class="card-footer">
                  <small class="text-muted">{{task.date}}</small>
                </div>
              </div>
            </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  
  <div class="container d-flex justify-content-center bg-body rounded">
    <h5><a href="{% url 'todolist:show_todolist' %}" class="btn btn-dark">Back to Top</a></h5>
  </div>

  <br>
  <br>
  {% endblock content %}
</body>

todolist/templates/todolist_new.html
{% extends 'base.html' %}


{% block content %}

{% include 'header.html' %}

<head>
    {% load static %}
    <!-- CSS LINKS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>
    
    $(document).ready(function () {
    getData();
     })
    // Return task data as json
    function getData() {
        $.ajax({
            url: "{% url 'todolist:get_task_json' %}",
            type: "GET",
            dataType: "json",
            success: function(data) {
                
                    $('#taskData').append(`   
                    <div class="container shadow p-3 mb-5">
                    <div class="h2"> ToDos </div>
                    <div class="d-flex align-content-center justify-content-center">

                    <div class="card bg-body rounded"">
                        <div class="card-body">
                            <h2> class="card-title">${data.fields.title}</h2>
                            <p class="card-text">${data.fields.description}</p>
                        </div>
                    </div>
                    `
                    );
                    
                }
            }
        )
    }

    // POST FROM USER SUBMISSION

    $('#form').on('submit', (e) => {
        e.preventDefault(); //stop normal form submit
        $.ajax({
            type: "POST",
            url: "/todolist/add/",
            data: {
                "title": $('#title').val(),
                "description": $('#description').val(),
            },
            success: (data) => {
                $("#taskData").html("");
                $('#taskModal').modal('hide');
                getData()
            },
        })
    })
    

    </script>

    
</head>

<body>
    <!-- UNTUK MODAL ADD TASK -->
    <div class="modal fade" id="taskModal" tabindex="-1" aria-labelledby="taskModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="taskModalLabel">Add New Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <!-- Form for modal -->
                <form action="/todolist/add/" method="POST" id="form">
                    {% csrf_token %}
                    <div class="modal-body">
                        <!-- Modal title input -->
                            <input type="text" class="form-control" id="title" name="title" placeholder="Title">
    
                        <!-- Modal desc input -->
                            <textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-success">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    </div class="container">
        <div id="taskData">
    </div>
    <div class="container d-flex justify-content-center bg-body rounded">
        <button type="button" class="btn-lg btn-warning" data-bs-toggle="modal" data-bs-target="#taskModal">Add Task</button>
    </div>
</body>
  {% endblock content %}